apiVersion: apps/v1
kind: Deployment
metadata:
  name: tn-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tn-manager
  template:
    metadata:
      labels:
        app: tn-manager
    spec:
      hostNetwork: true
      containers:
      - name: server
        image: alan0415/tn-manager:v0.3.0 #v0.2.1
        command: ["./TN-Manager", "--port", "8081"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
        ports:
        - containerPort: 8081
        #env:
        #- name: ENV 
        #  value: "PRODUCTION"
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
